#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RazBankingDroid.Resource", IsApplication=true)]

namespace RazBankingDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.Azure.Engagement.Xamarin.Resource.String.library_name = global::RazBankingDroid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int account = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int engagement_close = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int engagement_content_title = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int main = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int tmbtouch = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int action = 2131034115;
			
			// aapt resource value: 0x7f05000f
			public const int body = 2131034127;
			
			// aapt resource value: 0x7f050025
			public const int btnEnroll = 2131034149;
			
			// aapt resource value: 0x7f05001c
			public const int btnEnrollmentToMain = 2131034140;
			
			// aapt resource value: 0x7f050024
			public const int btnLogin = 2131034148;
			
			// aapt resource value: 0x7f050021
			public const int btnLoginStartRecording = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int btnLoginStopRecording = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int btnLoginToMain = 2131034147;
			
			// aapt resource value: 0x7f05001a
			public const int btnResetProfile = 2131034138;
			
			// aapt resource value: 0x7f050018
			public const int btnStartRecording = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int btnStopRecording = 2131034137;
			
			// aapt resource value: 0x7f050011
			public const int choices = 2131034129;
			
			// aapt resource value: 0x7f050001
			public const int engagement_button_bar = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int engagement_notification_area = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int engagement_notification_close = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int engagement_notification_close_area = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int engagement_notification_icon = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int engagement_notification_image = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int engagement_notification_message = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int engagement_notification_overlay = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int engagement_notification_text = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int engagement_notification_title = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int exit = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int imageView1 = 2131034112;
			
			// aapt resource value: 0x7f05001b
			public const int listView1 = 2131034139;
			
			// aapt resource value: 0x7f050010
			public const int question_title = 2131034128;
			
			// aapt resource value: 0x7f05000e
			public const int questions = 2131034126;
			
			// aapt resource value: 0x7f050012
			public const int textView1 = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int textView2 = 2131034132;
			
			// aapt resource value: 0x7f050016
			public const int textView3 = 2131034134;
			
			// aapt resource value: 0x7f05001f
			public const int textView5 = 2131034143;
			
			// aapt resource value: 0x7f050004
			public const int title = 2131034116;
			
			// aapt resource value: 0x7f05001e
			public const int txtConfidenceLevel = 2131034142;
			
			// aapt resource value: 0x7f050020
			public const int txtLoginVerificationPhrase = 2131034144;
			
			// aapt resource value: 0x7f050017
			public const int txtRemainingEnrollments = 2131034135;
			
			// aapt resource value: 0x7f05001d
			public const int txtStatus = 2131034141;
			
			// aapt resource value: 0x7f050015
			public const int txtVerificationPhrase = 2131034133;
			
			// aapt resource value: 0x7f050013
			public const int txtVerificationPhrases = 2131034131;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Account = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int engagement_button_bar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int engagement_content_title = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int engagement_loading = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int engagement_notification_area = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int engagement_notification_overlay = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int engagement_poll = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int engagement_poll_choice = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int engagement_poll_question = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int engagement_text_announcement = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int engagement_web_announcement = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Enrollment = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Login = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int Main = 2130903053;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
